# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='associated_currency',
            field=models.CharField(choices=[('S', 'SOLES'), ('D', 'DOLARES'), ('E', 'EUROS')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='num_account',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='num_card',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='num_cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='num_pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
